# Make a rectangular window !CHECK!
# Build the basic layout of the table
# Create commands for the individual buttons
# (Maybe do everything by testing on Hydrogen)
# For the love of god find out a way to fit everything in (either by changing the box size or something)
import tkinter 
import tkinter.font as tkfont
from tkinter import *
from tkinter import ttk
from tkinter.colorchooser import askcolor
from tkinter import messagebox
from PIL import ImageTk, Image
import os
os.system("pip install tkinter")
os.system("pip install PIL")
Enter = False

root = tkinter.Tk()
root.geometry("2000x600")
root.title('Periodic Table')




def HCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Hydrogen (H)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n1\n\nNumber of Protons:\n1\n\nNo. of Nutrons:\n0\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n1.0078 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -259.16°C\n(13.99 K)\n\nBoiling point:\n-252.87°C (20.28 K)\n\nDiscovery date:\n1766\n\n').grid(column=1, row=1)
def HeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Helium (He)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n2\n\nNumber of Protons:\n2\n\nNo. of Nutrons:\n2\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n4.0026 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Boiling point: -268.93°C\n(4.22 K)\n\nDiscovery date:\n1868\n\n').grid(column=1, row=1)
def LiCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Lithium (Li)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n3\n\nNumber of Protons:\n3\n\nNo. of Nutrons:\n3\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n6.9410 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 180.54°C\n(453.69 K)\n\nBoiling point:\n1342°C (1615.15 K)\n\nDiscovery date:\n1817\n\n').grid(column=1, row=1)
def BeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Berilium (Be)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n4\n\nNumber of Protons:\n4\n\nNo. of Nutrons:\n4\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n10.811 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1286.85°C\n(1560 K)\n\nBoiling point: 2469°C\n(2742.15 K)\n\nDiscovery date:\n1797\n\n').grid(column=1, row=1)
def BCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Boron (B)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n5\n\nNumber of Protons:\n5\n\nNo. of Nutrons:\n5\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n10.0122 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2076°C\n(2349.15 K)\n\nBoiling point: 4000°C\n(4273.15 K)\n\nDiscovery date:\n1808\n\n').grid(column=1, row=1)
def CCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Carbon (C)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n6\n\nNumber of Protons:\n6\n\nNo. of Nutrons:\n6\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n12.011 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'No other info').grid(column=1, row=1)
def NCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Nitrogen (N)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n7\n\nNumber of Protons:\n7\n\nNo. of Nutrons:\n7\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n14.007 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -210.01°C\n(63.14 K)\n\nBoiling point: -195.79°C\n(77.36 K)\n\nDiscovery date:\n1772').grid(column=1, row=1)
def OCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Oxygen (O)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n8\n\nNumber of Protons:\n8\n\nNo. of Nutrons:\n8\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n15.999 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -218.79°C\n(54.36 K)\n\nBoiling point: -182.96°C\n(90.19 K)\n\nDiscovery date:\n1774').grid(column=1, row=1)
def FCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Fluorine (F)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n9\n\nNumber of Protons:\n9\n\nNo. of Nutrons:\n9\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n18.998 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -219.62°C\n(53.53 K)\n\nBoiling point: -188.11°C\n(85.04 K)\n\nDiscovery date:\n1886').grid(column=1, row=1)
def NeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Neon (Ne)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n10\n\nNumber of Protons:\n10\n\nNo. of Nutrons:\n10\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n10.180 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -248.59°C\n(24.56 K)\n\nBoiling point: -246.05°C\n(27.1 K)\n\nDiscovery date:\n1898').grid(column=1, row=1)
def NaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Sodium (Na)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n11\n\nNumber of Protons:\n11\n\nNo. of Nutrons:\n11\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n22.990 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 97.79°C\n(370.94 K)\n\nBoiling point: 882.85°C\n(1156 K)\n\nDiscovery date:\n1807').grid(column=1, row=1)
def MgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Magnesium (Mg)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n12\n\nNumber of Protons:\n12\n\nNo. of Nutrons:\n12\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n24.305 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 650°C\n(923.15 K)\n\nBoiling point: 1091°C\n(1364.15 K)\n\nDiscovery date:\n1755').grid(column=1, row=1)
def AlCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Aluminum (Al)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n13\n\nNumber of Protons:\n13\n\nNo. of Nutrons:\n13\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n26.982 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 660.32°C\n(933.47 K)\n\nBoiling point: 2470°C\n(2743.15 K)\n\nDiscovery date:\n1825').grid(column=1, row=1)
def SiCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Silicon (Si)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n14\n\nNumber of Protons:\n14\n\nNo. of Nutrons:\n14\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n28.086 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1414°C\n(1687.15 K)\n\nBoiling point: 2355°C\n(2628.15 K)\n\nDiscovery date:\n1824').grid(column=1, row=1)
def PCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Phosphorus (P)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n15\n\nNumber of Protons:\n15\n\nNo. of Nutrons:\n15\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n30.974 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 44.1°C\n(317.25 K)\n\nBoiling point: 280.5°C\n(553.65 K)\n\nDiscovery date:\n1669').grid(column=1, row=1)
def SCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Sulfur (S)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n16\n\nNumber of Protons:\n16\n\nNo. of Nutrons:\n16\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n32.065 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 112.8°C\n(385.95 K)\n\nBoiling point: 444.6°C\n(717.75 K)').grid(column=1, row=1)
def ClCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("WIP ()")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n17\n\nNumber of Protons:\n17\n\nNo. of Nutrons:\n17\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n35.453 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -101.5°C\n(171.65 K)\n\nBoiling point: -34.04°C\n(239.11 K)\n\nDiscovery date:\n1774').grid(column=1, row=1)
def ArCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Argon (Ar)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n18\n\nNumber of Protons:\n18\n\nNo. of Nutrons:\n18\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n39.948 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -189.35°C\n(83.8 K)\n\nBoiling point: -185.85°C\n(87.3 K)\n\nDiscovery date:\n1894').grid(column=1, row=1)
def KCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Potassium (K)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n19\n\nNumber of Protons:\n19\n\nNo. of Nutrons:\n19\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n39.098 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 63.5°C\n(336.65 K)\n\nBoiling point: 758.85°C\n(1032 K)\n\nDiscovery date:\n1807').grid(column=1, row=1)
def CaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Calcium (Ca)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n20\n\nNumber of Protons:\n20\n\nNo. of Nutrons:\n20\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n40.078 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 842°C\n(1115.15 K)\n\nBoiling point: 1483.85°C\n(1757 K)\n\nDiscovery date:\n1808').grid(column=1, row=1)
def ScCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Scandium (Sc)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n21\n\nNumber of Protons:\n21\n\nNo. of Nutrons:\n21\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n44.956 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1540.85°C\n(1814 K)\n\nBoiling point: 2835.85°C\n(3109 K)\n\nDiscovery date:\n1879').grid(column=1, row=1)
def TiCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Titanium (Ti)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n22\n\nNumber of Protons:\n22\n\nNo. of Nutrons:\n22\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n47.867 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1668°C\n(1941.15 K)\n\nBoiling point: 3286.85°C\n(3560 K)\n\nDiscovery date:\n1791').grid(column=1, row=1)
def VCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Vandium (V)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n23\n\nNumber of Protons:\n23\n\nNo. of Nutrons:\n23\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n50.942 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1910°C\n(2183.15 K)\n\nBoiling point: 3407°C\n(3680.15 K)\n\nDiscovery date:\n1801').grid(column=1, row=1)
def CrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Cromium (Cr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n24\n\nNumber of Protons:\n24\n\nNo. of Nutrons:\n\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n51.996 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1907°C\n(2180.15 K)\n\nBoiling point: 2671.85°C\n(2945 K)\n\nDiscovery date:\n1797').grid(column=1, row=1)
def MnCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Manganese (Mn)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n25\n\nNumber of Protons:\n25\n\nNo. of Nutrons:\n30\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n54.938 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1246°C\n(1519.15 K)\n\nBoiling point: 2061°C\n(2334.15 K)\n\nDiscovery date:\n1774').grid(column=1, row=1)
def FeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Iron (Fe)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n26\n\nNumber of Protons:\n26\n\nNo. of Nutrons:\n30\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n55.845 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1538°C\n(1811.15 K)\n\nBoiling point: 2862°C\n(3135.15 K)').grid(column=1, row=1)
def CoCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Cobalt (Co)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n27\n\nNumber of Protons:\n27\n\nNo. of Nutrons:\n32\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n58.933 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1495°C\n(1768.15 K)\n\nBoiling point: 2869.85°C\n(3143 K)\n\nDiscovery date:\n1735').grid(column=1, row=1)
def NiCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Nickel (Ni)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n28\n\nNumber of Protons:\n28\n\nNo. of Nutrons:\n31\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n58.693 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1455°C\n(1728.15 K)\n\nBoiling point: 2913°C\n(3186.15 K)\n\nDiscovery date:\n1751').grid(column=1, row=1)
def CuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Copper (Cu)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n29\n\nNumber of Protons:\n35\n\nNo. of Nutrons:\n29\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n63.546 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1084.62°C\n(1357.77 K)\n\nBoiling point: 2562°C\n(2835.15 K)').grid(column=1, row=1)
def ZnCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Zinc (Zn)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n30\n\nNumber of Protons:\n35\n\nNo. of Nutrons:\n30\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n65.380 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 419.53°C\n(692.68 K)\n\nBoiling point: 907°C\n(1180.15 K)\n\nDiscovery date:\n1746').grid(column=1, row=1)
def GaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Gallium (Ga)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n31\n\nNumber of Protons:\n39\n\nNo. of Nutrons:\n31\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n69.723 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 29.76°C\n(302.91 K)\n\nBoiling point: 2400°C\n(2673.15 K)\n\nDiscovery date:\n1875').grid(column=1, row=1)
def GeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Germanium (Ge)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n32\n\nNumber of Protons:\n32\n\nNo. of Nutrons:\n32\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n72.640 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 938.25°C\n(1211.4 K)\n\nBoiling point: 2833°C\n(3106.15 K)\n\nDiscovery date:\n1886').grid(column=1, row=1)
def AsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Arsenic (As)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n33\n\nNumber of Protons:\n33\n\nNo. of Nutrons:\n33\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n74.922 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 816.85°C\n(1090 K)\n\nBoiling point: 613°C\n(886.15 K)\n\nDiscovery date:\n1250').grid(column=1, row=1)
def SeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Selenium (Se)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n34\n\nNumber of Protons:\n34\n\nNo. of Nutrons:\n34\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n78.960 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 220.85°C\n(494 K)\n\nBoiling point: 684.85°C\n(958 K)\n\nDiscovery date:\n1817').grid(column=1, row=1)
def BrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Bromine (Br)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n35\n\nNumber of Protons:\n35\n\nNo. of Nutrons:\n35\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n79.904 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -7.2°C\n(265.95 K)\n\nBoiling point: 58.8°C\n(331.95 K)\n\nDiscovery date:\n1826').grid(column=1, row=1)
def KrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Krypton (Kr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n36\n\nNumber of Protons:\n36\n\nNo. of Nutrons:\n36\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n83.798 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -157.36°C\n(115.79 K)\n\nBoiling point: -153.41°C\n(119.74 K)\n\nDiscovery date:\n1898').grid(column=1, row=1)
def RbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Rubidium (Rb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n37\n\nNumber of Protons:\n37\n\nNo. of Nutrons:\n37\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n85.468 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 39.48°C\n(312.63 K)\n\nBoiling point: 688°C\n(961.15 K)\n\nDiscovery date:\n1861').grid(column=1, row=1)
def SrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Strontium (Sr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n38\n\nNumber of Protons:\n38\n\nNo. of Nutrons:\n38\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n87.620 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 777°C\n(1050.15 K)\n\nBoiling point: 1381.85°C\n(16555 K)\n\nDiscovery date:\n1790').grid(column=1, row=1)
def YCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Yttrium (Y)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n39\n\nNumber of Protons:\n39\n\nNo. of Nutrons:\n39\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n88.906 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1526°C\n(1799.15 K)\n\nBoiling point: 3337.85°C\n(3611 K)\n\nDiscovery date:\n1794').grid(column=1, row=1)
def ZrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Zirconium (Zr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n40\n\nNumber of Protons:\n40\n\nNo. of Nutrons:\n40\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n91.224 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1854°C\n(2128 K)\n\nBoiling point: 4408.85°C\n(4682 K)\n\nDiscovery date:\n1789').grid(column=1, row=1)
def NbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Niobium (Nb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n41\n\nNumber of Protons:\n41\n\nNo. of Nutrons:\n41\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n92.906 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2477°C\n(2750.15 K)\n\nBoiling point: 4927°C\n(5200.15 K)\n\nDiscovery date:\n1801').grid(column=1, row=1)
def MoCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Molybdenum (Mo)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n42\n\nNumber of Protons:\n42\n\nNo. of Nutrons:\n42\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n95.950 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2622.85°C\n(2896 K)\n\nBoiling point: 4638.85°C\n(4912 K)\n\nDiscovery date:\n1778').grid(column=1, row=1)
def TcCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Technetium (Tc)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n43\n\nNumber of Protons:\n43\n\nNo. of Nutrons:\n43\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n98 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2203.85°C\n(2477 K)\n\nBoiling point: 4264.85°C\n(4538 K)\n\nDiscovery date:\n1937').grid(column=1, row=1)
def RuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Ruthenium (Ru)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n44\n\nNumber of Protons:\n44\n\nNo. of Nutrons:\n44\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n101.07 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2334°C\n(2607.15 K)\n\nBoiling point: 4150°C\n(4423.15 K)\n\nDiscovery date:\n1844').grid(column=1, row=1)
def RhCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Rhodium (Rh)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n45\n\nNumber of Protons:\n45\n\nNo. of Nutrons:\n45\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n102.91 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1962.85°C\n(2236 K)\n\nBoiling point: 3696.85°C\n(3970 K)\n\nDiscovery date:\n1803').grid(column=1, row=1)
def PdCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Palladium (Pd)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n46\n\nNumber of Protons:\n46\n\nNo. of Nutrons:\n46\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n106.42 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1554.9°C\n(1828.05 K)\n\nBoiling point: 2963°C\n(3236.15 K)\n\nDiscovery date:\n1803').grid(column=1, row=1)
def AgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Silver (Ag)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n47\n\nNumber of Protons:\n47\n\nNo. of Nutrons:\n47\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n107.87 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 961.78°C\n(1234.93 K)\n\nBoiling point: 2162°C\n(2435.15 K)').grid(column=1, row=1)
def CdCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Cadmium (Cd)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n48\n\nNumber of Protons:\n48\n\nNo. of Nutrons:\n48\n\nNo. of Valence Electrons:\n12\n\nAtomic mass:\n112.41 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 321.11°C\n(594.26 K)\n\nBoiling point: 766.85°C\n(1040 K)\n\nDiscovery date:\n1817').grid(column=1, row=1)
def InCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Indium (In)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n49\n\nNumber of Protons:\n49\n\nNo. of Nutrons:\n49\n\nNo. of Valence Electrons:\n13\n\nAtomic mass:\n114.82 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 156.63°C\n(429.78 K)\n\nBoiling point: 2072°C\n(2345.15 K)\n\nDiscovery date:\n1863').grid(column=1, row=1)
def SnCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Tin (Sn)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n50\n\nNumber of Protons:\n50\n\nNo. of Nutrons:\n50\n\nNo. of Valence Electrons:\n14\n\nAtomic mass:\n118.71 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 231.93°C\n(505.08 K)\n\nBoiling point: 2602°C\n(2875.15 K)').grid(column=1, row=1)
def SbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Antimony (Sb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n51\n\nNumber of Protons:\n51\n\nNo. of Nutrons:\n51\n\nNo. of Valence Electrons:\n15\n\nAtomic mass:\n121.76 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 630.63°C\n(903.78 K)\n\nBoiling point: 1586.85°C\n(1860 K)').grid(column=1, row=1)
def TeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Tellurium (Te)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n52\n\nNumber of Protons:\n52\n\nNo. of Nutrons:\n52\n\nNo. of Valence Electrons:\n16\n\nAtomic mass:\n127.60 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 449.51°C\n(722.66 K)\n\nBoiling point: 987.85°C\n(1261 K)\n\nDiscovery date:\n1782').grid(column=1, row=1)
def ICom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Iodine (I)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n53\n\nNumber of Protons:\n53\n\nNo. of Nutrons:\n53\n\nNo. of Valence Electrons:\n17\n\nAtomic mass:\n126.90 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 113.7°C\n(386.85 K)\n\nBoiling point: 184.3°C\n(457.45 K)\n\nDiscovery date:\n1811').grid(column=1, row=1)
def XeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Xenon (Xe)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n54\n\nNumber of Protons:\n54\n\nNo. of Nutrons:\n54\n\nNo. of Valence Electrons:\n18\n\nAtomic mass:\n131.29 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -111.75°C\n(161.4 K)\n\nBoiling point: -108.12°C\n(165.03 K)\n\nDiscovery date:\n1898').grid(column=1, row=1)
def CsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Caesium (Cs)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n55\n\nNumber of Protons:\n55\n\nNo. of Nutrons:\n55\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n132.91 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 28.44°C\n(301.59 K)\n\nBoiling point: 670.85°C\n(944 K)\n\nDiscovery date:\n1860').grid(column=1, row=1)
def BaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Barium (Ba)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n56\n\nNumber of Protons:\n56\n\nNo. of Nutrons:\n56\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n137.33 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 727°C\n(1000.15 K)\n\nBoiling point: 1897°C\n(2170.15 K)\n\nDiscovery date:\n1808').grid(column=1, row=1)
def HfCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Hafnium (Hf)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n72\n\nNumber of Protons:\n72\n\nNo. of Nutrons:\n72\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n178.49 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2227°C\n(2500.15 K)\n\nBoiling point: 4601.85°C\n(4875 K)\n\nDiscovery date:\n1923').grid(column=1, row=1)
def TaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Tantalum (Ta)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n73\n\nNumber of Protons:\n73\n\nNo. of Nutrons:\n73\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n180.95 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 3019.85°C\n(3293 K)\n\nBoiling point: 5456.85°C\n(5730 K)\n\nDiscovery date:\n1802').grid(column=1, row=1)
def WCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Tungsten (W)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n74\n\nNumber of Protons:\n74\n\nNo. of Nutrons:\n74\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n183.84 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 3422°C\n(3695.15 K)\n\nBoiling point: 5555°C\n(5828.15 K)\n\nDiscovery date:\n1783').grid(column=1, row=1)
def ReCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Rhenium (Re)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n75\n\nNumber of Protons:\n75\n\nNo. of Nutrons:\n75\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n186.21 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 3181.85°C\n(3455 K)\n\nBoiling point: 5596.85°C\n(5870 K)\n\nDiscovery date:\n1925').grid(column=1, row=1)
def OsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Osmium (Os)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n76\n\nNumber of Protons:\n76\n\nNo. of Nutrons:\n76\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n190.23 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 3033°C\n(3306.15 K)\n\nBoiling point: 5026.85°C\n(5300 K)\n\nDiscovery date:\n1803').grid(column=1, row=1)
def IrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Iridium (Ir)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n77\n\nNumber of Protons:\n77\n\nNo. of Nutrons:\n77\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n192.22 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2446°C\n(2719.15 K)\n\nBoiling point: 4428°C\n(4701.15 K)\n\nDiscovery date:\n1803').grid(column=1, row=1)
def PtCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Platinum (Pt)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n78\n\nNumber of Protons:\n78\n\nNo. of Nutrons:\n78\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n195.08 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1768.3°C\n(2041.45 K)\n\nBoiling point: 3825°C\n(4098.15 K)\n\nDiscovery date:\n1735').grid(column=1, row=1)
def AuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Gold (Au)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n79\n\nNumber of Protons:\n79\n\nNo. of Nutrons:\n79\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n196.97 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1064.18°C\n(1337.33 K)\n\nBoiling point: 2836°C\n(3109.15 K)').grid(column=1, row=1)
def HgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Mercury (Hg)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n80\n\nNumber of Protons:\n80\n\nNo. of Nutrons:\n80\n\nNo. of Valence Electrons:\n12\n\nAtomic mass:\n200.59 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -38.83°C\n(234.32 K)\n\nBoiling point: 356.73°C\n(629.88 K)').grid(column=1, row=1)
def TlCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Thallium (Tl)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n81\n\nNumber of Protons:\n81\n\nNo. of Nutrons:\n81\n\nNo. of Valence Electrons:\n13\n\nAtomic mass:\n204.38 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 303.85°C\n(577 K)\n\nBoiling point: 1472.85°C\n(1746 K)\n\nDiscovery date:\n1861').grid(column=1, row=1)
def PbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Lead (Pb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n82\n\nNumber of Protons:\n82\n\nNo. of Nutrons:\n82\n\nNo. of Valence Electrons:\n14\n\nAtomic mass:\n207.20 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 327.5°C\n(600.65 K)\n\nBoiling point: 1749°C\n(2022.15 K)').grid(column=1, row=1)
def BiCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Bismuth (Bi)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n83\n\nNumber of Protons:\n83\n\nNo. of Nutrons:\n83\n\nNo. of Valence Electrons:\n15\n\nAtomic mass:\n208.98 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 271.44°C\n(544.59 K)\n\nBoiling point: 1564°C\n(1837.15 K)\n\nDiscovery date:\n1753').grid(column=1, row=1)
def PoCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Polonium (Po)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n84\n\nNumber of Protons:\n84\n\nNo. of Nutrons:\n84\n\nNo. of Valence Electrons:\n16\n\nAtomic mass:\n209 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 253.85°C\n(527 K)\n\nBoiling point: 962°C\n(1235.15 K)\n\nDiscovery date:\n1898').grid(column=1, row=1)
def AtCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Astatine (At)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n85\n\nNumber of Protons:\n85\n\nNo. of Nutrons:\n85\n\nNo. of Valence Electrons:\n17\n\nAtomic mass:\n210 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 301.85°C\n(575 K)\n\nBoiling point: 336.85°C\n(610 K)\n\nDiscovery date:\n1940').grid(column=1, row=1)
def RnCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Radon (Rn)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n86\n\nNumber of Protons:\n86\n\nNo. of Nutrons:\n86\n\nNo. of Valence Electrons:\n18\n\nAtomic mass:\n222 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: -71.15°C\n(202 K)\n\nBoiling point: -61.7°C\n(211.45 K)\n\nDiscovery date:\n1900').grid(column=1, row=1)
def FrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Francium (Fr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n87\n\nNumber of Protons:\n87\n\nNo. of Nutrons:\n87\n\nNo. of Valence Electrons:\n1\n\nAtomic mass:\n223 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 27°C\n(300.15 K)\n\nBoiling point: 677°C\n(950.15 K)\n\nDiscovery date:\n1939').grid(column=1, row=1)
def RaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Radium (Ra)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n88\n\nNumber of Protons:\n88\n\nNo. of Nutrons:\n88\n\nNo. of Valence Electrons:\n2\n\nAtomic mass:\n226 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 696°C\n(969.15 K)\n\nBoiling point: 1737°C\n(2010.15 K)\n\nDiscovery date:\n189').grid(column=1, row=1)
def RfCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Rutherfordium (Rf)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n104\n\nNumber of Protons:\n104\n\nNo. of Nutrons:\n104\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n267 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 2100°C\n(2373.15 K)\n\nDiscovery date:\n1964').grid(column=1, row=1)
def DbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Dubnium (Db)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n105\n\nNumber of Protons:\n105\n\nNo. of Nutrons:\n105\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n262 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1967').grid(column=1, row=1)
def SgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Seaborgium (Sg)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n106\n\nNumber of Protons:\n106\n\nNo. of Nutrons:\n106\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n269 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1974').grid(column=1, row=1)
def BhCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Bohrium (Bh)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n107\n\nNumber of Protons:\n107\n\nNo. of Nutrons:\n107\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n264 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1981').grid(column=1, row=1)
def HsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Hassium (Hs)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n108\n\nNumber of Protons:\n108\n\nNo. of Nutrons:\n108\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n269 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1984').grid(column=1, row=1)
def MtCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Meitnerium (Mt)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n109\n\nNumber of Protons:\n109\n\nNo. of Nutrons:\n109\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n278 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1982').grid(column=1, row=1)
def DsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Darmstadtium (Ds)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n110\n\nNumber of Protons:\n110\n\nNo. of Nutrons:\n110\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n281 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:1994').grid(column=1, row=1)
def RgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Roentgenium (Rg)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n111\n\nNumber of Protons:\n111\n\nNo. of Nutrons:\n111\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n282 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1994').grid(column=1, row=1)
def CnCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Copernicium (Cn)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n112\n\nNumber of Protons:\n112\n\nNo. of Nutrons:\n112\n\nNo. of Valence Electrons:\n12\n\nAtomic mass:\n285 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n1996').grid(column=1, row=1)
def NhCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Nihonium (Nh)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n113\n\nNumber of Protons:\n113\n\nNo. of Nutrons:\n113\n\nNo. of Valence Electrons:\n13\n\nAtomic mass:\n286 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n2003').grid(column=1, row=1)
def FlCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Flerovium (Fl)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n114\n\nNumber of Protons:\n114\n\nNo. of Nutrons:\n114\n\nNo. of Valence Electrons:\n14\n\nAtomic mass:\n289 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:1998').grid(column=1, row=1)
def McCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Moscovium (Mc)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n115\n\nNumber of Protons:\n115\n\nNo. of Nutrons:\n115\n\nNo. of Valence Electrons:\n15\n\nAtomic mass:\n289 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n2003').grid(column=1, row=1)
def LvCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Livermorium (Lv)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n116\n\nNumber of Protons:\n116\n\nNo. of Nutrons:\n116\n\nNo. of Valence Electrons:\n16\n\nAtomic mass:\n293 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n2000').grid(column=1, row=1)
def TsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Tennessine (Ts)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n117\n\nNumber of Protons:\n117\n\nNo. of Nutrons:\n117\n\nNo. of Valence Electrons:\n17\n\nAtomic mass:\n294 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Boiling point: 610°C\n(883.15 K)\n\nDiscovery date:\n2010').grid(column=1, row=1)
def OgCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Oganesson (Og)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n118\n\nNumber of Protons:\n118\n\nNo. of Nutrons:\n118\n\nNo. of Valence Electrons:\n18\n\nAtomic mass:\n294 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Discovery date:\n2002').grid(column=1, row=1)
def LaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Lanthanum (La)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n57\n\nNumber of Protons:\n57\n\nNo. of Nutrons:\n57\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n138.91 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 920°C\n(1193.15 K)\n\nBoiling point: 3463.85°C\n(3737 K)\n\nDiscovery date:\n1839').grid(column=1, row=1)
def CeCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Cerium (Ce)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n58\n\nNumber of Protons:\n58\n\nNo. of Nutrons:\n58\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n140.12 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 795°C\n(1068.15 K)\n\nBoiling point: 3257°C\n(3530.15 K)\n\nDiscovery date:\n1803').grid(column=1, row=1)
def PrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Praseodymium (Pr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n59\n\nNumber of Protons:\n59\n\nNo. of Nutrons:\n59\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n140.91 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 930.85°C\n(1204 K)\n\nBoiling point: 3520°C\n(3793.15 K)\n\nDiscovery date:\n1885').grid(column=1, row=1)
def NdCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Neodymium (Nd)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n60\n\nNumber of Protons:\n60\n\nNo. of Nutrons:\n60\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n144.24 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1020.85°C\n(1294 K)\n\nBoiling point: 3073.85°C\n(3347 K)\n\nDiscovery date:\n1885').grid(column=1, row=1)
def PmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Promethium (Pm)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n61\n\nNumber of Protons:\n61\n\nNo. of Nutrons:\n61\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n145 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1041.85°C\n(1315 K)\n\nBoiling point: 2999.85°C\n(3273 K)\n\nDiscovery date:\n1945').grid(column=1, row=1)
def SmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Samarium (Sm)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n62\n\nNumber of Protons:\n62\n\nNo. of Nutrons:\n62\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n150.36 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1072°C\n(1345.15 K)\n\nBoiling point: 1793.85°C\n(2067 K)\n\nDiscovery date:\n1879').grid(column=1, row=1)
def EuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Europium (Eu)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n63\n\nNumber of Protons:\n63\n\nNo. of Nutrons:\n63\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n151.96 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 826°C\n(1099.15 K)\n\nBoiling point: 1529°C\n(1802.15 K)\n\nDiscovery date:\n1901').grid(column=1, row=1)
def GdCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Gadolinium (Gd)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n64\n\nNumber of Protons:\n64\n\nNo. of Nutrons:\n64\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n157.25 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1311.85°C\n(1585 K)\n\nBoiling point: 3271.85°C\n(3545 K)\n\nDiscovery date:\n1880').grid(column=1, row=1)
def TbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Terbium (Tb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n65\n\nNumber of Protons:\n65\n\nNo. of Nutrons:\n65\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n158.93u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1355.85°C\n(1629 K)\n\nBoiling point: 3230°C\n(3503.15 K)\n\nDiscovery date:\n1843').grid(column=1, row=1)
def DyCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Dysprosium (Dy)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n66\n\nNumber of Protons:\n66\n\nNo. of Nutrons:\n66\n\nNo. of Valence Electrons:\n12\n\nAtomic mass:\n162.5 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1411.85°C\n(1685 K)\n\nBoiling point: 2566.85°C\n(2840 K)\n\nDiscovery date:\n1886').grid(column=1, row=1)
def HoCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Holmium (Ho)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n67\n\nNumber of Protons:\n67\n\nNo. of Nutrons:\n67\n\nNo. of Valence Electrons:\n13\n\nAtomic mass:\n164.93 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1474°C\n(1747.15 K)\n\nBoiling point: 2694.85°C\n(2968 K)\n\nDiscovery date:\n1878').grid(column=1, row=1)
def ErCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Erbium (Er)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n68\n\nNumber of Protons:\n68\n\nNo. of Nutrons:\n68\n\nNo. of Valence Electrons:\n14\n\nAtomic mass:\n167.26 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1528.85°C\n(1802 K)\n\nBoiling point: 2868°C\n(3141.15 K)\n\nDiscovery date:\n1843').grid(column=1, row=1)
def TmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Thulium (Tm)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n69\n\nNumber of Protons:\n69\n\nNo. of Nutrons:\n69\n\nNo. of Valence Electrons:\n15\n\nAtomic mass:\n168.93 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1544.85°C\n(1818 K)\n\nBoiling point: 1950°C\n(2223.15 K)\n\nDiscovery date:\n1879').grid(column=1, row=1)
def YbCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Ytterbium (Yb)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n70\n\nNumber of Protons:\n70\n\nNo. of Nutrons:\n70\n\nNo. of Valence Electrons:\n16\n\nAtomic mass:\n173.04 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 819°C\n(1092.15 K)\n\nBoiling point: 1195.85°C\n(1469 K)\n\nDiscovery date:\n1878').grid(column=1, row=1)
def LuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Lutetium (Lu)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n71\n\nNumber of Protons:\n71\n\nNo. of Nutrons:\n71\n\nNo. of Valence Electrons:\n17\n\nAtomic mass:\n174.97 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1662.85°C\n(1936 K)\n\nBoiling point: 3402°C\n(3675.15 K)\n\nDiscovery date:\n1907').grid(column=1, row=1)
def AcCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Actinium (Ac)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n89\n\nNumber of Protons:\n89\n\nNo. of Nutrons:\n89\n\nNo. of Valence Electrons:\n3\n\nAtomic mass:\n227 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1050°C\n(1323.15 K)\n\nBoiling point: 3196.85°C\n(3470 K)\n\nDiscovery date:\n1899').grid(column=1, row=1)
def ThCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Thorium (Th)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n90\n\nNumber of Protons:\n90\n\nNo. of Nutrons:\n90\n\nNo. of Valence Electrons:\n4\n\nAtomic mass:\n232.04 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1754.85°C\n(2028 K)\n\nBoiling point: 4786.85°C\n(5060 K)\n\nDiscovery date:\n1828').grid(column=1, row=1)
def PaCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Protactinium (Pa)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n91\n\nNumber of Protons:\n91\n\nNo. of Nutrons:\n91\n\nNo. of Valence Electrons:\n5\n\nAtomic mass:\n231.04 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1568°C\n(1841.15 K)\n\nBoiling point: 4000°C\n(4273.15 K)\n\nDiscovery date:\n1913').grid(column=1, row=1)
def UCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Uranium (U)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n92\n\nNumber of Protons:\n92\n\nNo. of Nutrons:\n92\n\nNo. of Valence Electrons:\n6\n\nAtomic mass:\n238.03 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1132.2°C\n(1405.35 K)\n\nBoiling point: 4131°C\n(4404.15 K)\n\nDiscovery date:\n1789').grid(column=1, row=1)
def NpCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Neptunium (Np)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n93\n\nNumber of Protons:\n93\n\nNo. of Nutrons:\n93\n\nNo. of Valence Electrons:\n7\n\nAtomic mass:\n237.05 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 644°C\n(917.15 K)\n\nBoiling point: 3901.85°C\n(4175 K)\n\nDiscovery date:\n1940').grid(column=1, row=1)
def PuCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Plutonium (Pu)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n94\n\nNumber of Protons:\n94\n\nNo. of Nutrons:\n94\n\nNo. of Valence Electrons:\n8\n\nAtomic mass:\n244 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 639.4°C\n(912.55 K)\n\nBoiling point: 3231.85°C\n(3505 K)\n\nDiscovery date:\n1940').grid(column=1, row=1)
def AmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Americium (Am)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n95\n\nNumber of Protons:\n95\n\nNo. of Nutrons:\n95\n\nNo. of Valence Electrons:\n9\n\nAtomic mass:\n243 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1175.85°C\n(1449 K)\n\nBoiling point: 2606.85°C\n(2880 K)\n\nDiscovery date:\n1944').grid(column=1, row=1)
def CmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Curium (Cm)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n96\n\nNumber of Protons:\n96\n\nNo. of Nutrons:\n96\n\nNo. of Valence Electrons:\n10\n\nAtomic mass:\n247 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1346.85°C\n(1620 K)\n\nBoiling point: 3109.85°C\n(3383 K)\n\nDiscovery date:\n1944').grid(column=1, row=1)
def BkCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Berkelium (Bk)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n97\n\nNumber of Protons:\n97\n\nNo. of Nutrons:\n97\n\nNo. of Valence Electrons:\n11\n\nAtomic mass:\n247 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 984.85°C\n(1258 K)\n\nBoiling point: 2627°C\n(2900.15 K)\n\nDiscovery date:\n1949').grid(column=1, row=1)
def CfCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Californium (Cf)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n98\n\nNumber of Protons:\n98\n\nNo. of Nutrons:\n98\n\nNo. of Valence Electrons:\n12\n\nAtomic mass:\n251 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 898.85°C\n(1172 K)\n\nBoiling point: 1472°C\n(1745.15 K)\n\nDiscovery date:\n1950').grid(column=1, row=1)
def EsCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Einsteinium (Es)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n99\n\nNumber of Protons:\n99\n\nNo. of Nutrons:\n99\n\nNo. of Valence Electrons:\n13\n\nAtomic mass:\n252 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'This info is still in development').grid(column=1, row=1)
def FmCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Fermium (Fm)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n100\n\nNumber of Protons:\n100\n\nNo. of Nutrons:\n100\n\nNo. of Valence Electrons:\n14\n\nAtomic mass:\n257 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1526.85°C\n(1800 K)\n\nDiscovery date:\n1953').grid(column=1, row=1)
def MdCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Mendelevium (Md)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n101\n\nNumber of Protons:\n101\n\nNo. of Nutrons:\n101\n\nNo. of Valence Electrons:\n15\n\nAtomic mass:\n258 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 826.85°C\n(1100 K)\n\nDiscovery date:\n1955').grid(column=1, row=1)
def NoCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Nobelium (No)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n102\n\nNumber of Protons:\n102\n\nNo. of Nutrons:\n102\n\nNo. of Valence Electrons:\n16\n\nAtomic mass:\n259 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 826.85°C\n(1100 K)\n\nDiscovery date:\n1958').grid(column=1, row=1)
def LrCom():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("Lawrencium (Lr)")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n103\n\nNumber of Protons:\n103\n\nNo. of Nutrons:\n103\n\nNo. of Valence Electrons:\n17\n\nAtomic mass:\n262 u\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'Melting point: 1627°C\n(1900.15 K)\n\nDiscovery date:\n1961').grid(column=1, row=1)



def Com():
    Ele = Toplevel(root)
    Ele.geometry("300x500")
    Ele.title("WIP ()")
    BasInfo = ttk.Label(Ele, text= 'No. of Electrons:\n\n\nNumber of Protons:\n\n\nNo. of Nutrons:\n\n\nNo. of Valence Electrons:\n\n\nAtomic mass:\nu\n').grid(column=1,row=0)
    AdvInfo = ttk.Label(Ele, text= 'This info is still in development').grid(column=1, row=1)



#goffy little thing
def Password():
    def Raffa_png():
        Raf = Toplevel(root)
        Raf.geometry("197x238")
        Raf.title("Raffa.png")
        frame = Frame(Raf, width=600, height=400)
        frame.pack()
        frame.place(anchor='center', relx=0.5, rely=0.5)
        img = ImageTk.PhotoImage(Image.open('Rafaa.png'))
        label = Label(frame, image = img)
        label.pack()
        Raf.mainloop()
    def get_data():
        label.config(text= entry.get(), font= ('Helvetica 13'))
        text = entry.get()
        if text.lower() == "raffa.png":
            label.config(text= 'Access Granted')
            Raffa_png()
        else:
            label.config(text='Access Denied')
            label.place(relx= .5, rely= .6, anchor= CENTER)
    Pass = Toplevel(root)
    Pass.geometry("600x300")
    Pass.title("La-Lu")
    entry = Entry(Pass, width= 42)
    label = Label(Pass, text='', font=('Helvetica 13'))
    entry.place(relx= .5, rely= .5, anchor= CENTER)
    label.pack
    Button(Pass, text= 'Submit', command=get_data).place(relx= .5, rely= .7, anchor= CENTER)


def SourcesCom():
    Sou = Toplevel(root)
    Sou.geometry("600x500")
    Sou.title("Sources")
    Bas = ttk.Label(Sou, text= 'Sources for the info that i have used for this project:')
    BasI = ttk.Label(Sou, text= 'http://hobart.k12.in.us/ksms/PeriodicTable/atomicnumber.htm')
    BasIn = ttk.Label(Sou, text= 'https://www.google.com/search?client=opera-gx&q=periodic+table&sourceid=opera&ie=UTF-8&oe=UTF-8')
    Bas.pack(anchor='nw',pady=2)
    BasI.pack(anchor='nw',pady=2)
    BasIn.pack(anchor='nw',pady=2)
    print('\n\nSources for the info that i have used for this project:\n\nhttp://hobart.k12.in.us/ksms/PeriodicTable/atomicnumber.htm\nhttps://www.google.com/search?client=opera-gx&q=periodic+table&sourceid=opera&ie=UTF-8&oe=UTF-8')
    Name = ttk.Label(Sou, text='Created by:   glooman777')
    Name.pack(anchor='nw',pady=2)



# all the buttons named "space" are just to make the rows and columns work properly
Space = Label(root, text= '',).grid(column=0, row=0)

# this is the actual buttons for the table
HB = ttk.Button(root, text= 'H', command=HCom,).grid(column=0, row=1)
HeB = ttk.Button(root, text= 'He', command=HeCom).grid(column=17, row=1)
LiB = ttk.Button(root, text= 'Li', command=LiCom).grid(column=0, row=2)
BeB = ttk.Button(root, text= 'Be', command=BeCom).grid(column=1, row=2)
BB = ttk.Button(root, text= 'B', command=BCom).grid(column=12, row=2)
CB = ttk.Button(root, text= 'C', command=CCom).grid(column=13, row=2)
NB = ttk.Button(root, text= 'N', command=NCom).grid(column=14, row=2)
OB = ttk.Button(root, text= 'O', command=OCom).grid(column=15, row=2)
FB = ttk.Button(root, text= 'F', command=FCom).grid(column=16, row=2)
NeB = ttk.Button(root, text= 'Ne', command=NeCom).grid(column=17, row=2)
NaB = ttk.Button(root, text= 'Na', command=NaCom).grid(column=0, row=3)
MgB = ttk.Button(root, text= 'Mg', command=MgCom).grid(column=1, row=3)
AlB = ttk.Button(root, text= 'Al', command=AlCom).grid(column=12, row=3)
SiB = ttk.Button(root, text= 'Si', command=SiCom).grid(column=13, row=3)
PB = ttk.Button(root, text= 'P', command=PCom).grid(column=14, row=3)
SB = ttk.Button(root, text= 'S', command=SCom).grid(column=15, row=3)
ClB = ttk.Button(root, text= 'Cl', command=ClCom).grid(column=16, row=3)
ArB = ttk.Button(root, text= 'Ar', command=ArCom).grid(column=17, row=3)
KB = ttk.Button(root, text= 'K', command=KCom).grid(column=0, row=4)
CaB = ttk.Button(root, text= 'Ca', command=CaCom).grid(column=1, row=4)
ScB = ttk.Button(root, text= 'Sc', command=ScCom).grid(column=2, row=4)
TiB = ttk.Button(root, text= 'Ti', command=TiCom).grid(column=3, row=4)
VB = ttk.Button(root, text= 'V', command=VCom).grid(column=4, row=4)
CrB = ttk.Button(root, text= 'Cr', command=CrCom).grid(column=5, row=4)
MnB = ttk.Button(root, text= 'Mn', command=MnCom).grid(column=6, row=4)
FeB = ttk.Button(root, text= 'Fe', command=FeCom).grid(column=7, row=4)
CoB = ttk.Button(root, text= 'Co', command=CoCom).grid(column=8, row=4)
NiB = ttk.Button(root, text= 'Ni', command=NiCom).grid(column=9, row=4)
CuB = ttk.Button(root, text= 'Cu', command=CuCom).grid(column=10, row=4)
ZnB = ttk.Button(root, text= 'Zn', command=ZnCom).grid(column=11, row=4)
GaB = ttk.Button(root, text= 'Ga', command=GaCom).grid(column=12, row=4)
GeB = ttk.Button(root, text= 'Ge', command=GeCom).grid(column=13, row=4)
AsB = ttk.Button(root, text= 'As', command=AsCom).grid(column=14, row=4)
SeB = ttk.Button(root, text= 'Se', command=SeCom).grid(column=15, row=4)
BrB = ttk.Button(root, text= 'Br', command=BrCom).grid(column=16, row=4)
KrB = ttk.Button(root, text= 'Kr', command=KrCom).grid(column=17, row=4)
RbB = ttk.Button(root, text= 'Rb', command=RbCom).grid(column=0, row=5)
SrB = ttk.Button(root, text= 'Sr', command=SrCom).grid(column=1, row=5)
YB = ttk.Button(root, text= 'Y', command=YCom).grid(column=2, row=5)
ZrB = ttk.Button(root, text= 'Zr', command=ZrCom).grid(column=3, row=5)
NbB = ttk.Button(root, text= 'Nb', command=NbCom).grid(column=4, row=5)
MoB = ttk.Button(root, text= 'Mo', command=MoCom).grid(column=5, row=5)
TcB = ttk.Button(root, text= 'Tc', command=TcCom).grid(column=6, row=5)
RuB = ttk.Button(root, text= 'Ru', command=RuCom).grid(column=7, row=5)
RhB = ttk.Button(root, text= 'Rh', command=RhCom).grid(column=8, row=5)
PdB = ttk.Button(root, text= 'Pd', command=PdCom).grid(column=9, row=5)
AgB = ttk.Button(root, text= 'Ag', command=AgCom).grid(column=10, row=5)
CdB = ttk.Button(root, text= 'Cd', command=CdCom).grid(column=11, row=5)
InB = ttk.Button(root, text= 'In', command=InCom).grid(column=12, row=5)
SnB = ttk.Button(root, text= 'Sn', command=SnCom).grid(column=13, row=5)
SbB = ttk.Button(root, text= 'Sb', command=SbCom).grid(column=14, row=5)
TeB = ttk.Button(root, text= 'Te', command=TeCom).grid(column=15, row=5)
IB = ttk.Button(root, text= 'I', command=ICom).grid(column=16, row=5)
XeB = ttk.Button(root, text= 'Xe', command=XeCom).grid(column=17, row=5)
CsB = ttk.Button(root, text= 'Cs', command=CsCom).grid(column=0, row=6)
BaB = ttk.Button(root, text= 'Ba', command=BaCom).grid(column=1, row=6)
LaLuB = ttk.Button(root, text= 'La-Lu', command=Password).grid(column=2, row=6)
HfB = ttk.Button(root, text= 'Hf', command=HfCom).grid(column=3, row=6)
TaB = ttk.Button(root, text= 'Ta', command=TaCom).grid(column=4, row=6)
WB = ttk.Button(root, text= 'W', command=WCom).grid(column=5, row=6)
ReB = ttk.Button(root, text= 'Re', command=ReCom).grid(column=6, row=6)
OsB = ttk.Button(root, text= 'Os', command=OsCom).grid(column=7, row=6)
IrB = ttk.Button(root, text= 'Ir', command=IrCom).grid(column=8, row=6)
PtB = ttk.Button(root, text= 'Pt', command=PtCom).grid(column=9, row=6)
AuB = ttk.Button(root, text= 'Au', command=AuCom).grid(column=10, row=6)
HgB = ttk.Button(root, text= 'Hg', command=HgCom).grid(column=11, row=6)
TlB = ttk.Button(root, text= 'Tl', command=TlCom).grid(column=12, row=6)
PbB = ttk.Button(root, text= 'Pb', command=PbCom).grid(column=13, row=6)
BiB = ttk.Button(root, text= 'Bi', command=BiCom).grid(column=14, row=6)
PoB = ttk.Button(root, text= 'Po', command=PoCom).grid(column=15, row=6)
AtB = ttk.Button(root, text= 'At', command=AtCom).grid(column=16, row=6)
RnB = ttk.Button(root, text= 'Rn', command=RnCom).grid(column=17, row=6)
FrB = ttk.Button(root, text= 'Fr', command=FrCom).grid(column=0, row=7)
RaB = ttk.Button(root, text= 'Ra', command=RaCom).grid(column=1, row=7)
AcLrB = ttk.Button(root, text= 'Ac-Lr', command=None).grid(column=2, row=7)
RfB = ttk.Button(root, text= 'Rf', command=RfCom).grid(column=3, row=7)
DbB = ttk.Button(root, text= 'Db', command=DbCom).grid(column=4, row=7)
SgB = ttk.Button(root, text= 'Sg', command=SgCom).grid(column=5, row=7)
BhB = ttk.Button(root, text= 'Bh', command=BhCom).grid(column=6, row=7)
HsB = ttk.Button(root, text= 'Hs', command=HsCom).grid(column=7, row=7)
MtB = ttk.Button(root, text= 'Mt', command=MtCom).grid(column=8, row=7)
DsB = ttk.Button(root, text= 'Ds', command=DsCom).grid(column=9, row=7)
RgB = ttk.Button(root, text= 'Rg', command=RgCom).grid(column=10, row=7)
CnB = ttk.Button(root, text= 'Cn', command=CnCom).grid(column=11, row=7)
NhB = ttk.Button(root, text= 'Nh', command=NhCom).grid(column=12, row=7)
FlB = ttk.Button(root, text= 'Fl', command=FlCom).grid(column=13, row=7)
McB = ttk.Button(root, text= 'Mc', command=McCom).grid(column=14, row=7)
LvB = ttk.Button(root, text= 'Lv', command=LvCom).grid(column=15, row=7)
TsB = ttk.Button(root, text= 'Ts', command=TsCom).grid(column=16, row=7)
OgB = ttk.Button(root, text= 'Og', command=OgCom).grid(column=17, row=7)
Space1 = ttk.Label(root, text= '').grid(column=0, row=8)
LaB = ttk.Button(root, text= 'La', command=LaCom).grid(column=2, row=9)
CeB = ttk.Button(root, text= 'Ce', command=CeCom).grid(column=3, row=9)
PrB = ttk.Button(root, text= 'Pr', command=PrCom).grid(column=4, row=9)
NdB = ttk.Button(root, text= 'Nd', command=NdCom).grid(column=5, row=9)
PmB = ttk.Button(root, text= 'Pm', command=PmCom).grid(column=6, row=9)
SmB = ttk.Button(root, text= 'Sm', command=SmCom).grid(column=7, row=9)
EuB = ttk.Button(root, text= 'Eu', command=EuCom).grid(column=8, row=9)
GdB = ttk.Button(root, text= 'Gd', command=GdCom).grid(column=9, row=9)
TbB = ttk.Button(root, text= 'Tb', command=TbCom).grid(column=10, row=9)
DyB = ttk.Button(root, text= 'Dy', command=DyCom).grid(column=11, row=9)
HoB = ttk.Button(root, text= 'Ho', command=HoCom).grid(column=12, row=9)
ErB = ttk.Button(root, text= 'Er', command=ErCom).grid(column=13, row=9)
TmB = ttk.Button(root, text= 'Tm', command=TmCom).grid(column=14, row=9)
YbB = ttk.Button(root, text= 'Yb', command=YbCom).grid(column=15, row=9)
LuB = ttk.Button(root, text= 'Lu', command=LuCom).grid(column=16, row=9)
AcB = ttk.Button(root, text= 'Ac', command=AcCom).grid(column=2, row=10)
ThB = ttk.Button(root, text= 'Th', command=ThCom).grid(column=3, row=10)
PaB = ttk.Button(root, text= 'Pa', command=PaCom).grid(column=4, row=10)
UB = ttk.Button(root, text= 'U', command=UCom).grid(column=5, row=10)
NbB = ttk.Button(root, text= 'Nb', command=NbCom).grid(column=6, row=10)
PuB = ttk.Button(root, text= 'Pu', command=PuCom).grid(column=7, row=10)
AmB = ttk.Button(root, text= 'Am', command=AmCom).grid(column=8, row=10)
CmB = ttk.Button(root, text= 'Cm', command=CmCom).grid(column=9, row=10)
BkB = ttk.Button(root, text= 'Bk', command=BkCom).grid(column=10, row=10)
CfB = ttk.Button(root, text= 'Cf', command=CfCom).grid(column=11, row=10)
EsB = ttk.Button(root, text= 'Es', command=EsCom).grid(column=12, row=10)
FmB = ttk.Button(root, text= 'Fm', command=FmCom).grid(column=13, row=10)
MdB = ttk.Button(root, text= 'Md', command=MdCom).grid(column=14, row=10)
NoB = ttk.Button(root, text= 'No', command=NoCom).grid(column=15, row=10)
LrB = ttk.Button(root, text= 'Lr', command=LrCom).grid(column=16, row=10)

Space = ttk.Label(root, text='\n').grid(column=16, row=11)
Space = ttk.Label(root, text='\n').grid(column=16, row=12)
Space = ttk.Label(root, text='\n').grid(column=16, row=13)
Space = ttk.Label(root, text='\n').grid(column=16, row=14)
Space = ttk.Label(root, text='\n').grid(column=16, row=15)
Space = ttk.Label(root, text='\n').grid(column=16, row=16)
Space = ttk.Label(root, text='\n').grid(column=16, row=17)
Space = ttk.Label(root, text='\n').grid(column=16, row=18)
Space = ttk.Label(root, text='\n').grid(column=16, row=19)
Space = ttk.Label(root, text='\n').grid(column=16, row=20)
SourcesB = ttk.Button(root, text= 'Sources', command=SourcesCom).grid(column=17, row=20)


root.mainloop()